run:
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck         # catch unchecked errors
    - govet            # catch suspicious constructs
    - staticcheck      # advanced correctness checks
    - gosimple         # detect simpler code rewrites
    - gofmt            # code style
    - goimports        # import formatting
    - misspell         # common typos
    - ineffassign      # detect ineff assignments
    - deadcode         # remove unused code
    - unused           # detect unused vars, funcs, types

linters-settings:
  misspell:
    locale: US
