name: sims

on:
  push:
    branches:
      - master

jobs:
  simulations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - uses: actions/checkout@v4

      - name: build
        run: |
          make build

      - name: run sims
        run: |
          make test-sim
